services:
    web_production:
        build: .
        container_name: web_production
        command: gunicorn main_app.wsgi:application --bind 0.0.0.0:8000 --workers 3
        volumes:
            - .:/app
        environment:
            - DJANGO_SETTINGS_MODULE=main_app.settings.production
            - ENVIRONMENT=production
        depends_on:
            - db_production

    web_staging:
        build: .
        container_name: web_staging
        command: gunicorn main_app.wsgi:application --bind 0.0.0.0:8000 --workers 3
        volumes:
            - .:/app
        environment:
            - DJANGO_SETTINGS_MODULE=main_app.settings.development
            - ENVIRONMENT=staging
        depends_on:
            - db_staging

    nginx_production:
        image: nginx:stable-alpine
        container_name: nginx_production
        ports:
            - "80:80" # Producción en puerto 80
        volumes:
            - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web_production

    nginx_staging:
        image: nginx:stable-alpine
        container_name: nginx_staging
        ports:
            - "8000:80" # Staging en puerto 8000 (en el host)
        volumes:
            - ./nginx.staging.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web_staging

    db_production:
        image: postgres:13
        container_name: postgres_prod
        environment:
            POSTGRES_DB: mantenimiento_db_prod
            POSTGRES_USER: admin_mantenimiento
            POSTGRES_PASSWORD: admin_mantenimiento
        ports:
            - "5432:5432"
        volumes:
            - pgdata_prod:/var/lib/postgresql/data

    db_staging:
        image: postgres:13
        container_name: postgres_staging
        environment:
            POSTGRES_DB: mantenimiento_db_dev
            POSTGRES_USER: admin_dev
            POSTGRES_PASSWORD: admin_dev
        ports:
            - "5433:5432" # Staging se expone en puerto 5433 en el host, aunque internamente usa 5432
        volumes:
            - pgdata_dev:/var/lib/postgresql/data

volumes:
    pgdata_prod:
    pgdata_dev:
