version: '3.9'

services:
    web:
        build: .
        command: gunicorn mantenimiento_programado.wsgi:application --bind 0.0.0.0:8000 --workers 3
        volumes:
            - .:/app
        environment:
            - POSTGRES_DB=mantenimiento_db
            - POSTGRES_USER=admin_mantenimiento
            - POSTGRES_PASSWORD=admin_mantenimiento
        depends_on:
            - db

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80" # Publicamos el puerto 80 del contenedor en el host
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - web

    db:
        image: postgres:13
        environment:
            POSTGRES_DB: mantenimiento_db
            POSTGRES_USER: admin_mantenimiento
            POSTGRES_PASSWORD: admin_mantenimiento
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
