# Generated by Django 5.1.7 on 2025-04-12 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('idEncargado', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('idMantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('idMaquina', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMaquina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('idPieza', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPieza', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PiezaMaquina',
            fields=[
                ('idPiezaMaquina', models.AutoField(primary_key=True, serialize=False)),
                ('idMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maquina')),
                ('idPieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pieza')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('idEncargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.encargado')),
                ('idMantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mantenimiento')),
                ('idMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maquina')),
                ('idPieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pieza')),
            ],
        ),
    ]
