# Generated by Django 5.1.7 on 2025-04-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargado',
            old_name='idEncargado',
            new_name='id_encargado',
        ),
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='idMantenimiento',
            new_name='id_mantenimiento',
        ),
        migrations.RenameField(
            model_name='maquina',
            old_name='idMaquina',
            new_name='id_maquina',
        ),
        migrations.RenameField(
            model_name='maquina',
            old_name='tipoMaquina',
            new_name='tipo_maquina',
        ),
        migrations.RenameField(
            model_name='pieza',
            old_name='idPieza',
            new_name='id_pieza',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='idEncargado',
            new_name='id_encargado',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='idMantenimiento',
            new_name='id_mantenimiento',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='idMaquina',
            new_name='id_maquina',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='idTarea',
            new_name='id_tarea',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pieza',
            name='tipoPieza',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='idPieza',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='instrucciones',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='intervalo',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='parte_maquina',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('lubricar', 'Lubricar'), ('pruebas', 'Pruebas'), ('inspeccion', 'Inspección'), ('reajuste', 'Reajuste')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maquina',
            name='piezas',
            field=models.ManyToManyField(to='api.pieza'),
        ),
        migrations.AddField(
            model_name='pieza',
            name='cantidad',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pieza',
            name='tipo_pieza',
            field=models.CharField(choices=[('rodamiento', 'Rodamiento'), ('aceite', 'Aceite'), ('tornillo', 'Tornillo'), ('correa', 'Correa'), ('filtro', 'Filtro')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PiezasUtilizadas',
            fields=[
                ('id_piezas_utilizadas', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tarea')),
            ],
        ),
        migrations.DeleteModel(
            name='PiezaMaquina',
        ),
    ]
