# Generated by Django 5.1.7 on 2025-04-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_idencargado_encargado_id_encargado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezasutilizadas',
            name='pieza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.pieza'),
            preserve_default=False,
        ),
    ]
