# Generated by Django 5.1.7 on 2025-04-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_piezasutilizadas_pieza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='piezas',
        ),
    ]
