# Generated by Django 5.1.7 on 2025-03-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='mantenimiento.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenimiento.encargado')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenimiento.maquina')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenimiento.pieza')),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mantenimiento.tipomantenimiento')),
            ],
        ),
        migrations.AddField(
            model_name='maquina',
            name='ultima_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas_con_ultima_tarea', to='mantenimiento.tareamantenimiento'),
        ),
    ]
