# Generated by Django 5.1.7 on 2025-05-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionesMaquina',
            fields=[
                ('id_opcion_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_maquina', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='maquina',
            name='tipo_maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.opcionesmaquina'),
        ),
    ]
