# Generated by Django 5.1.7 on 2025-05-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mantenimiento", "0002_opcionesmaquina_alter_maquina_tipo_maquina"),
    ]

    operations = [
        migrations.AddField(
            model_name="encargado",
            name="apellido",
            field=models.CharField(default="Apellido Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="encargado",
            name="nombre",
            field=models.CharField(default="Nombre Desconocido", max_length=100),
        ),
        migrations.AddField(
            model_name="encargado",
            name="telefono",
            field=models.CharField(default="0123456789", max_length=15),
        ),
    ]
