# Generated by Django 5.1.7 on 2025-05-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_encargado_apellido_encargado_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargado',
            name='telefono',
            field=models.CharField(default='Telefono Desconocido', max_length=15),
        ),
    ]
