# Generated by Django 5.1.7 on 2025-05-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_tarea_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='anio_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='anio_fabricacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='apodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='maquinas/'),
        ),
        migrations.AddField(
            model_name='maquina',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.encargado'),
        ),
    ]
